version: '3.6'
services:
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: aha
    image: 'postgres:16-alpine'
    ports:
      - 5432:5432
    volumes:
      - 'aha_postgres:/var/lib/postgresql/data'

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/aha?sslmode=disable
    depends_on:
      - postgres

volumes:
  aha_postgres:
